trigger:
  branches:
    include:
      - feature-app1
      - main

parameters:
  - name: environment
    displayName: EnvironmentSelection
    type: string
    default: dev
    values:
      - dev
      - test
      - prod

variables:
  - name: system.debug
    value: true

pool: 
  name: Aarush_agent_pool
  demands:
    - Agent.Name -equals Aarush_agent

stages:
  - stage: A
    displayName: Precommit
    jobs:
    - job: A
      displayName: TerraformCodequalityCheck
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/${{ parameters.environment }}'
          backendServiceArm: 'myservconn'
          backendAzureRmOverrideSubscriptionID: 'b197523b-6a83-4a07-8922-3be74b9d39be'
          backendAzureRmResourceGroupName: 'TestRG'
          backendAzureRmStorageAccountName: 'testbackendsa'
          backendAzureRmContainerName: 'testsc'
          backendAzureRmKey: 'terraformdev20260719.tfstate'
          